# Generated by Django 4.1.3 on 2022-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
