# Generated by Django 4.1.3 on 2022-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Śniadania', 'Śniadania'), ('Przystawki', 'Przystawki'), ('Zupy', 'Zupy'), ('Dania główne', 'Dania główne'), ('Ciasta i desery', 'Ciasta i desery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(max_length=200),
        ),
    ]
