# Generated by Django 4.1.3 on 2022-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(choices=[('Ś', 'Śniadania'), ('P', 'Przystawki'), ('Z', 'Zupy'), ('DG', 'Dania główne'), ('D', 'Ciasta i desery')], default='Dania główne', to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
